### ISSUE TITLE
Bug em ocultar as images no inicio

### ISSUE THREAD

**Issue by mosiahrs** [Samuelloliiveira/memory-game#1]
## Erro - Imagens não ocultam

<img src="https://user-images.githubusercontent.com/100864562/185916563-290d34b1-3620-4013-8aba-aa4663e81df0.png" width="400">

Erro só é constatado no navegador Mozila Firefox, ao testar no Chrome a execução do jogo flui normalmente.

**Comment by Samuelloliiveira** [comment]
Resolvido. Era só add backface-visibility: hidden; para a imagem do back
